name: Hardhat Test
run-name: Running Hardhat tests
on:
  push:
    paths: 
      - "contracts/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install -g pnpm@8.6.2
          pnpm install

      - name: Set contracts as cwd 
        run: cd contracts
        
      - name: Run Hardhat tests
        run: |
          npx hardhat test